# 基础镜像
FROM redis
# author
MAINTAINER wangscaler

# 挂载目录
VOLUME /home/chat/redis
# 创建目录
RUN mkdir -p /home/chat/redis
# 指定路径
WORKDIR /home/chat/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/chat/redis/redis.conf
