# 基础镜像
FROM nacos/nacos-server
# author
MAINTAINER wangscaler
# 挂载目录
VOLUME /home/chat/nacos
# 创建目录
RUN mkdir -p /home/chat/nacos
# 复制conf文件到路径
# COPY ./nacos/conf/application.properties /home/chat/nacos/conf/application.properties
